apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: your-service-a-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          value: "yb-masters.mynamespace.svc.cluster.local"
        - name: DATABASE_PORT
          value: "5433"
        - name: DATABASE_USER
          value: "admin"
        - name: DATABASE_PASSWORD
          value: "password"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"



