apiVersion: v1
kind: Service
metadata:
  name: yb-tserver-service
spec:
  selector:
    app: yugabyte
  ports:
    - name: ysql  # Add a name for the first port
      protocol: TCP
      port: 5433  # YSQL (PostgreSQL-compatible)
      targetPort: 5433
    - name: ycql  # Add a name for the second port
      protocol: TCP
      port: 9042  # YCQL (Cassandra-compatible)
      targetPort: 9042


